"use client";

import { useState, useEffect } from "react";
import {
  Star,
  Eye,
  Check,
  X,
  Trash2,
  ArrowLeft,
  Plus,
} from "lucide-react";

export default function AdminReviewsPage() {
  const [reviews, setReviews] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [actionLoading, setActionLoading] = useState({});
  const [isAdmin, setIsAdmin] = useState(true); // Assuming admin for this page

  // State for new review form
  const [newName, setNewName] = useState("");
  const [newRating, setNewRating] = useState(0);
  const [newReviewText, setNewReviewText] = useState("");
  const [newCountry, setNewCountry] = useState("");
  const [addingReview, setAddingReview] = useState(false);

  useEffect(() => {
    fetchReviews();
  }, []);

  // Fetch reviews
  const fetchReviews = async () => {
    try {
      setLoading(true);
      const response = await fetch(`/api/admin/reviews/list`);
      if (!response.ok) {
        throw new Error("Failed to fetch reviews");
      }

      const data = await response.json();
      setReviews(data);
    } catch (error) {
      console.error("Fetch reviews error:", error);
    } finally {
      setLoading(false);
    }
  };

  // Handle adding a new review
  const handleAddReview = async (e) => {
    e.preventDefault();
    setAddingReview(true);
    setError("");
    setSuccess("");

    const newReview = {
      user_name: newName,
      rating: newRating,
      review_text: newReviewText,
      country: newCountry,
      status: "pending", // New reviews are pending by default
      created_at: new Date().toISOString(),
      // In a real app, product_id would be selected, and id would be generated by backend
      id: reviews.length + 1, // Placeholder ID
      product_name: "N/A", // Placeholder
      product_image: "", // Placeholder
    };

    try {
      // Simulate API call
      // const response = await fetch("/api/admin/reviews/add", {
      //   method: "POST",
      //   headers: { "Content-Type": "application/json" },
      //   body: JSON.stringify(newReview),
      // });
      // if (!response.ok) {
      //   throw new Error("Failed to add review");
      // }

      setReviews((prevReviews) => [newReview, ...prevReviews]); // Add to local state
      setSuccess("Review added successfully! It is now pending approval.");
      setNewName("");
      setNewRating(0);
      setNewReviewText("");
      setNewCountry("");
      setTimeout(() => setSuccess(""), 3000);
    } catch (error) {
      console.error("Add review error:", error);
      setError("Failed to add review");
      setTimeout(() => setError(""), 3000);
    } finally {
      setAddingReview(false);
    }
  };

  // Approve review
  const approveReview = async (reviewId) => {
    try {
      setActionLoading((prev) => ({ ...prev, [reviewId]: "approving" }));

      const response = await fetch("/api/admin/reviews/approve", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ reviewId }),
      });

      if (!response.ok) {
        throw new Error("Failed to approve review");
      }

      setSuccess("Review approved successfully!");
      setTimeout(() => setSuccess(""), 3000);
      fetchReviews();
    } catch (error) {
      console.error("Approve review error:", error);
      setError("Failed to approve review");
      setTimeout(() => setError(""), 3000);
    } finally {
      setActionLoading((prev) => ({ ...prev, [reviewId]: null }));
    }
  };

  // Delete review
  const deleteReview = async (reviewId) => {
    if (
      !confirm(
        "Are you sure you want to delete this review? This action cannot be undone.",
      )
    ) {
      return;
    }

    try {
      setActionLoading((prev) => ({ ...prev, [reviewId]: "deleting" }));

      const response = await fetch("/api/admin/reviews/delete", {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ reviewId }),
      });

      if (!response.ok) {
        throw new Error("Failed to delete review");
      }

      setSuccess("Review deleted successfully!");
      setTimeout(() => setSuccess(""), 3000);
      fetchReviews();
    } catch (error) {
      console.error("Delete review error:", error);
      setError("Failed to delete review");
      setTimeout(() => setError(""), 3000);
    } finally {
      setActionLoading((prev) => ({ ...prev, [reviewId]: null }));
    }
  };

  // Render stars
  const renderStars = (rating, setRating = null) => {
    return [...Array(5)].map((_, i) => (
      <Star
        key={i}
        className={`w-5 h-5 cursor-pointer ${
          i < rating ? "text-[#ff00b3] fill-current" : "text-gray-300"
        }`}
        onClick={() => setRating && setRating(i + 1)}
      />
    ));
  };

  // Get status badge color
  const getStatusBadge = (status) => {
    const colors = {
      pending:
        "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200",
      approved:
        "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200",
      rejected: "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200",
    };

    return colors[status] || colors.pending;
  };

  return (
    <div className="min-h-screen bg-white dark:bg-[#121212]">
      {/* Header */}
      <div className="bg-white dark:bg-[#1E1E1E] border-b border-[#E9E9E9] dark:border-[#333333] px-6 py-4">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-4">
            <a
              href="/admin"
              className="flex items-center gap-2 text-[#7B7B7B] dark:text-[#A0A0A0] hover:text-[#ff00b3] transition-colors"
            >
              <ArrowLeft className="w-5 h-5" />
              Back to Dashboard
            </a>
            <div className="w-px h-6 bg-[#E9E9E9] dark:bg-[#333333]"></div>
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-full bg-gradient-to-r from-blue-500 to-blue-600 flex items-center justify-center">
                <Star className="w-5 h-5 text-white" />
              </div>
              <h1
                className="text-xl font-bold text-black dark:text-white"
                style={{
                  fontFamily:
                    'Montserrat, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
                }}
              >
                Add New Review
              </h1>
            </div>
          </div>
        </div>
      </div>

      <main className="max-w-7xl mx-auto px-6 py-8">
        {/* Success/Error Messages */}
        {success && (
          <div className="mb-6 p-4 bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-xl text-sm text-green-600 dark:text-green-400">
            {success}
          </div>
        )}

        {/* Add New Review Form */}
        <div className="mb-8 bg-white dark:bg-[#1E1E1E] border border-[#F1F1F4] dark:border-[#333333] rounded-2xl p-6">
          <h2
            className="text-xl font-bold text-black dark:text-white mb-6"
            style={{
              fontFamily:
                'Montserrat, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
            }}
          >
            Add New Review
          </h2>
          <form onSubmit={handleAddReview} className="space-y-5">
            <div>
              <label
                htmlFor="name"
                className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2"
              >
                Name
              </label>
              <input
                type="text"
                id="name"
                className="w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-gray-700 bg-gray-50 dark:bg-[#2A2A2A] text-black dark:text-white focus:ring-2 focus:ring-[#ff00b3] focus:border-transparent outline-none transition-all duration-200"
                placeholder="Customer Name"
                value={newName}
                onChange={(e) => setNewName(e.target.value)}
                required
              />
            </div>
            <div>
              <label
                htmlFor="rating"
                className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2"
              >
                Star Rating
              </label>
              <div className="flex items-center gap-1">
                {renderStars(newRating, setNewRating)}
              </div>
            </div>
            <div>
              <label
                htmlFor="reviewText"
                className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2"
              >
                Review
              </label>
              <textarea
                id="reviewText"
                rows="4"
                className="w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-gray-700 bg-gray-50 dark:bg-[#2A2A2A] text-black dark:text-white focus:ring-2 focus:ring-[#ff00b3] focus:border-transparent outline-none transition-all duration-200"
                placeholder="Write your review here..."
                value={newReviewText}
                onChange={(e) => setNewReviewText(e.target.value)}
                required
              ></textarea>
            </div>
            <div>
              <label
                htmlFor="country"
                className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2"
              >
                Country
              </label>
              <input
                type="text"
                id="country"
                className="w-full px-4 py-3 rounded-lg border border-gray-300 dark:border-gray-700 bg-gray-50 dark:bg-[#2A2A2A] text-black dark:text-white focus:ring-2 focus:ring-[#ff00b3] focus:border-transparent outline-none transition-all duration-200"
                placeholder="e.g., USA, Nigeria"
                value={newCountry}
                onChange={(e) => setNewCountry(e.target.value)}
                required
              />
            </div>
            <button
              type="submit"
              className="flex items-center gap-2 bg-[#ff00b3] hover:bg-[#FFB6C1 ] text-black font-semibold px-6 py-3 rounded-lg transition-all duration-300 disabled:opacity-50"
              disabled={addingReview}
            >
              <Plus className="w-5 h-5" />
              {addingReview ? "Adding Review..." : "Add Review"}
            </button>
          </form>
        </div>

        {/* Reviews List */}
        {loading ? (
          <div className="text-center py-12">
            <p className="text-[#7B7B7B] dark:text-[#A0A0A0]">
              Loading reviews...
            </p>
          </div>
        ) : reviews.length === 0 ? (
          <div className="text-center py-12">
            <Eye className="w-16 h-16 text-[#7B7B7B] dark:text-[#A0A0A0] mx-auto mb-4" />
            <h3
              className="text-black dark:text-white font-semibold text-xl mb-2"
              style={{
                fontFamily:
                  'Montserrat, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
              }}
            >
              No Reviews Found
            </h3>
            <p
              className="text-[#7B7B7B] dark:text-[#A0A0A0]"
              style={{
                fontFamily:
                  'Open Sans, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
              }}
            >
              No reviews have been added yet.
            </p>
          </div>
        ) : (
          <div className="space-y-6">
            {reviews.map((review) => (
              <div
                key={review.id}
                className="bg-white dark:bg-[#1E1E1E] border border-[#F1F1F4] dark:border-[#333333] rounded-2xl p-6 hover:shadow-lg transition-all duration-300"
              >
                <div className="flex flex-col lg:flex-row gap-6">
                  {/* Product Info */}
                  <div className="flex items-start gap-4 lg:w-1/3">
                    {review.product_image && (
                      <img
                        src={review.product_image}
                        alt={review.product_name}
                        className="w-16 h-16 object-cover rounded-lg"
                      />
                    )}
                    <div>
                      <h3
                        className="text-black dark:text-white font-semibold mb-1"
                        style={{
                          fontFamily:
                            'Montserrat, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
                        }}
                      >
                        {review.product_name}
                      </h3>
                      <p
                        className="text-[#7B7B7B] dark:text-[#A0A0A0] text-sm"
                        style={{
                          fontFamily:
                            'Open Sans, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
                        }}
                      >
                        Review #{review.id}
                      </p>
                    </div>
                  </div>

                  {/* Review Content */}
                  <div className="flex-1">
                    <div className="flex items-center justify-between mb-3">
                      <div className="flex items-center gap-3">
                        <span
                          className="text-black dark:text-white font-semibold"
                          style={{
                            fontFamily:
                              'Montserrat, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
                          }}
                        >
                          {review.user_name}
                        </span>
                        {review.country && ( // Display country if available
                          <span
                            className="text-[#7B7B7B] dark:text-[#A0A0A0] text-sm"
                            style={{
                              fontFamily:
                                'Open Sans, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
                            }}
                          >
                            ({review.country})
                          </span>
                        )}
                        <div className="flex items-center gap-1">
                          {renderStars(review.rating)}
                        </div>
                        <span
                          className={`px-2 py-1 rounded-full text-xs font-medium ${getStatusBadge(review.status)}`}
                          style={{
                            fontFamily:
                              'Montserrat, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
                          }}
                        >
                          {review.status.charAt(0).toUpperCase() +
                            review.status.slice(1)}
                        </span>
                      </div>

                      <span
                        className="text-[#7B7B7B] dark:text-[#A0A0A0] text-sm"
                        style={{
                          fontFamily:
                            'Open Sans, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
                        }}
                      >
                        {new Date(review.created_at).toLocaleDateString()}
                      </span>
                    </div>

                    {review.review_text && (
                      <p
                        className="text-[#7B7B7B] dark:text-[#A0A0A0] mb-4 leading-relaxed"
                        style={{
                          fontFamily:
                            'Open Sans, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
                        }}
                      >
                        "{review.review_text}"
                      </p>
                    )}

                    {review.email && (
                      <p
                        className="text-[#7B7B7B] dark:text-[#A0A0A0] text-sm mb-4"
                        style={{
                          fontFamily:
                            'Open Sans, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
                        }}
                      >
                        Email: {review.email}
                      </p>
                    )}

                    {/* Action Buttons */}
                    <div className="flex gap-3">
                      {review.status === "pending" && (
                        <button
                          onClick={() => approveReview(review.id)}
                          disabled={actionLoading[review.id] === "approving"}
                          className="flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg transition-all duration-300 disabled:opacity-50"
                          style={{
                            fontFamily:
                              'Montserrat, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
                          }}
                        >
                          <Check className="w-4 h-4" />
                          {actionLoading[review.id] === "approving"
                            ? "Approving..."
                            : "Approve"}
                        </button>
                      )}

                      <button
                        onClick={() => deleteReview(review.id)}
                        disabled={actionLoading[review.id] === "deleting"}
                        className="flex items-center gap-2 bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-lg transition-all duration-300 disabled:opacity-50"
                        style={{
                          fontFamily:
                            'Montserrat, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
                        }}
                      >
                        <Trash2 className="w-4 h-4" />
                        {actionLoading[review.id] === "deleting"
                          ? "Deleting..."
                          : "Delete"}
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
