// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/account/logout": {
    params: {};
  };
  "/account/signin": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/categories": {
    params: {};
  };
  "/admin/categories/add": {
    params: {};
  };
  "/admin/categories/edit/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/products": {
    params: {};
  };
  "/admin/products/add": {
    params: {};
  };
  "/admin/reviews": {
    params: {};
  };
  "/admin/reviews/add": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/products/:id": {
    params: {
      "id": string;
    };
  };
  "/reviews": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/account/logout" | "/account/signin" | "/admin" | "/admin/categories" | "/admin/categories/add" | "/admin/categories/edit/:id" | "/admin/products" | "/admin/products/add" | "/admin/reviews" | "/admin/reviews/add" | "/cart" | "/contact" | "/faq" | "/products" | "/products/:id" | "/reviews" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./about/page.jsx": {
    id: "about/page";
    page: "/about";
  };
  "./account/logout/page.jsx": {
    id: "account/logout/page";
    page: "/account/logout";
  };
  "./account/signin/page.jsx": {
    id: "account/signin/page";
    page: "/account/signin";
  };
  "./admin/page.jsx": {
    id: "admin/page";
    page: "/admin";
  };
  "./admin/categories/page.jsx": {
    id: "admin/categories/page";
    page: "/admin/categories";
  };
  "./admin/categories/add/page.jsx": {
    id: "admin/categories/add/page";
    page: "/admin/categories/add";
  };
  "./admin/categories/edit/[id]/page.jsx": {
    id: "admin/categories/edit/[id]/page";
    page: "/admin/categories/edit/:id";
  };
  "./admin/products/page.jsx": {
    id: "admin/products/page";
    page: "/admin/products";
  };
  "./admin/products/add/page.jsx": {
    id: "admin/products/add/page";
    page: "/admin/products/add";
  };
  "./admin/reviews/page.jsx": {
    id: "admin/reviews/page";
    page: "/admin/reviews";
  };
  "./admin/reviews/add/page.jsx": {
    id: "admin/reviews/add/page";
    page: "/admin/reviews/add";
  };
  "./cart/page.jsx": {
    id: "cart/page";
    page: "/cart";
  };
  "./contact/page.jsx": {
    id: "contact/page";
    page: "/contact";
  };
  "./faq/page.jsx": {
    id: "faq/page";
    page: "/faq";
  };
  "./products/page.jsx": {
    id: "products/page";
    page: "/products";
  };
  "./products/[id]/page.jsx": {
    id: "products/[id]/page";
    page: "/products/:id";
  };
  "./reviews/page.jsx": {
    id: "reviews/page";
    page: "/reviews";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "about/page": typeof import("./src/app/./about/page.jsx");
  "account/logout/page": typeof import("./src/app/./account/logout/page.jsx");
  "account/signin/page": typeof import("./src/app/./account/signin/page.jsx");
  "admin/page": typeof import("./src/app/./admin/page.jsx");
  "admin/categories/page": typeof import("./src/app/./admin/categories/page.jsx");
  "admin/categories/add/page": typeof import("./src/app/./admin/categories/add/page.jsx");
  "admin/categories/edit/[id]/page": typeof import("./src/app/./admin/categories/edit/[id]/page.jsx");
  "admin/products/page": typeof import("./src/app/./admin/products/page.jsx");
  "admin/products/add/page": typeof import("./src/app/./admin/products/add/page.jsx");
  "admin/reviews/page": typeof import("./src/app/./admin/reviews/page.jsx");
  "admin/reviews/add/page": typeof import("./src/app/./admin/reviews/add/page.jsx");
  "cart/page": typeof import("./src/app/./cart/page.jsx");
  "contact/page": typeof import("./src/app/./contact/page.jsx");
  "faq/page": typeof import("./src/app/./faq/page.jsx");
  "products/page": typeof import("./src/app/./products/page.jsx");
  "products/[id]/page": typeof import("./src/app/./products/[id]/page.jsx");
  "reviews/page": typeof import("./src/app/./reviews/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};